# Generated by Django 4.2.2 on 2023-08-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CV',
            new_name='Resume',
        ),
    ]
